---
- name: Show "is now Reachable" lines from Asterisk logs
  hosts: all                  # AWX Job Template inventory/limit controls targets
  gather_facts: false
  become: true                # needed on most systems to read /var/log/asterisk/full

  vars:
    log_path: "/var/log/asterisk/full"
    match_text: "is now Reachable"

  tasks:
    - name: Check if Asterisk log exists
      ansible.builtin.stat:
        path: "{{ log_path }}"
      register: asterisk_log

    - name: Read matching lines (if file exists)
      ansible.builtin.shell: |
        set -o pipefail
        grep -F "{{ match_text }}" "{{ log_path }}" || true
      args:
        executable: /bin/bash
      register: reachable
      changed_when: false
      when: asterisk_log.stat.exists

    - name: Display results for this host
      ansible.builtin.debug:
        msg: |-
          ==== {{ inventory_hostname }} ====
          {% if not asterisk_log.stat.exists %}
          {{ log_path }} not found
          {% elif reachable.stdout %}
          {{ reachable.stdout }}
          {% else %}
          (no matches)
          {% endif %}
