---
- name: Show "is now Reachable" lines from Asterisk logs
  hosts: FreePBX
  gather_facts: false
  become: true                 # usually required to read /var/log/asterisk/full

  tasks:
    - name: Confirm the Asterisk full log exists
      ansible.builtin.stat:
        path: /var/log/asterisk/full
      register: asterisk_log

    - name: Read matching lines (if file exists)
      ansible.builtin.shell: |
        set -o pipefail
        grep -F "is now Reachable" /var/log/asterisk/full || true
      args:
        executable: /bin/bash
      register: reachable
      changed_when: false
      when: asterisk_log.stat.exists

    - name: Display results for this host
      ansible.builtin.debug:
        msg: |-
          ==== {{ inventory_hostname }} ====
          {% if not asterisk_log.stat.exists %}
          /var/log/asterisk/full not found
          {% elif reachable.stdout %}
          {{ reachable.stdout }}
          {% else %}
          (no matches)
          {% endif %}
