# ansible-playbook 

- hosts: all
  become: yes
  tasks: 
   - name: upgrade os in debian based servers
     apt: 
       upgrade: dist
       update_cache: yes
       autoremove: yes
   - name: Check if reboot required
     stat: 
       path: /var/run/reboot-required
     register: reboot_required_file
     
   - name: Reboot if required
     reboot:
     when: reboot_required_file.stat.exists == true
     
