# ansible-playbook 

- name: Dist-upgrade Ubuntu 24.x hosts and reboot if needed
  hosts: all
  become: yes
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Ensure apt works and python3-apt is present (first-contact bootstrap)
      raw: |
        set -e
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y --no-install-recommends python3 python3-apt
      args:
        executable: /bin/bash
      changed_when: false

    - name: Reset connection so Ansible switches from raw to normal modules
      ansible.builtin.meta: reset_connection

    - name: Gather facts now that Python deps are in place
      ansible.builtin.setup:

  tasks:
    - name: Upgrade OS on Debian/Ubuntu family (dist-upgrade)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes
        autoclean: yes
        lock_timeout: 600
        dpkg_options: "--force-confdef --force-confold"
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after dist-upgrade"
        reboot_timeout: 900
      when: reboot_required_file.stat.exists | default(false)
     
