---
- name: Patch Debian 12.x and reboot if needed
  hosts: all
  become: yes
  gather_facts: yes
  serial: 1
  vars:
    apt_cache_valid_time: 3600
    reboot_timeout: 1800
  environment:
    DEBIAN_FRONTEND: noninteractive

  pre_tasks:
    - name: Determine if host is Debian 12.x
      ansible.builtin.set_fact:
        is_debian12: >-
          {{ ansible_facts.distribution == 'Debian'
             and ansible_facts.distribution_major_version == '12' }}

    - name: Skip non-Debian 12 hosts
      ansible.builtin.meta: end_host
      when: not is_debian12

    - name: Ensure update-notifier-common is present (for reboot-required flag)
      ansible.builtin.apt:
        name: update-notifier-common
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

  tasks:
    - name: Update apt cache (if stale)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Upgrade all packages (full-upgrade / dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after updates"
        reboot_timeout: "{{ reboot_timeout }}"
      when: reboot_required_file.stat.exists
