---
- name: Update apt systems and reboot if needed
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    apt_cache_valid_time: 3600   # seconds
    reboot_timeout: 1800         # seconds
  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Ensure reboot flag support is present
      ansible.builtin.apt:
        name: update-notifier-common
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Upgrade all packages (full upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot after updates"
        reboot_timeout: "{{ reboot_timeout }}"
      when: reboot_required.stat.exists
