---
- name: Update apt systems and reboot if needed
  hosts: all
  become: yes
  gather_facts: yes
  serial: 1
  vars:
    apt_cache_valid_time: 3600
    reboot_timeout: 1800
  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"

    - name: Full upgrade (kernel allowed)
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check Ubuntu/Debian reboot flag
      ansible.builtin.stat:
        path: /run/reboot-required
      register: rr

    - name: Check needrestart availability (Debian/Ubuntu fallback)
      ansible.builtin.stat:
        path: /usr/sbin/needrestart
      register: needrestart_bin

    - name: Query needrestart (non-interactive)
      ansible.builtin.command: needrestart -b -r a
      register: needrestart_rc
      changed_when: false
      failed_when: false
      when: not rr.stat.exists and needrestart_bin.stat.exists

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot after updates"
        reboot_timeout: "{{ reboot_timeout }}"
      when: rr.stat.exists or (needrestart_rc.rc is defined and needrestart_rc.rc != 0)
