---
- name: Update /etc/resolv.conf
  hosts: all
  become: true
  tasks:
    - name: Replace contents of /etc/resolv.conf
      copy:
        content: |
          # Custom resolv.conf file
          nameserver 97.105.10.61
          nameserver 34.27.145.229
          nameserver 104.154.199.153
          search kamin.us
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

