# ansible-playbook PBX.yml

- name : update the phone servers on all clients
  hosts: "*"
  tasks: 
   - name: upgrade the phone servers
     shell: fwconsole ma upgradeall 
     register: upgrade_output     
     
   - debug: 
         var: upgrade_output.stdout_lines
          
          
   - name: reload the fw console
     shell: fwconsole reload
     register: reload_output
     
   - debug: 
            var: reload_output.stdout_lines
    
   - name: Update the system
     shell: yum update -y
     register: update_output
     
   - debug: 
            var: update_output.stdout_lines
     
   - name: Upgrade the sytem
     shell: yum upgrade -y
     register: upgrade_output
     
   - debug: 
            var: upgrade_output.stdout_lines
     
     #- name : Reboots system
      # hosts: "*"
       #tasks:
       #- name: reboot the system
        # shell: reboot
          
          
