# ansible-playbook 

- name : update the phone servers on all clients
  hosts: "*"
  tasks: 
   - name: update the servers
     shell: sudo apt-get update
     register: update_output     
     
   - debug: 
         var: update_output.stdout_lines
          
   - name: upgrade the servers
     shell: sudo apt-get upgrade -y
     register: upgrade_output
     
   - debug: 
            var: upgrade_output.stdout_lines    
   
