# ansible-playbook 

- hosts: all
  become: yes
  tasks: 
   - name: upgrade the cloud dns servers
     apt: 
       upgrade: yes
       update_cache: yes
       autoremove: yes
 register: upgrade_output     
     
  - debug: 
        var: upgrade_output.stdout_lines
          
